#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

    - name: Detect OS
      shell: 
        cmd: ". /etc/os-release; echo $ID"
        executable: /bin/bash
      register: os

    - name: add kernel parameters
      blockinfile:
        path: "{{ startup_kernel_args_actions[os.stdout]['grub_path'] }}"
        create: yes
        block: |
          GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} {{ wl_kernel_args.values() | join(' ') }}"
      register: kargs
      ignore_errors: yes

    - name: update grub
      shell: "{{ startup_kernel_args_actions[os.stdout]['update_grub_cmd'] }}"
      when: (kargs.msg == 'Block inserted') or (kargs.msg == 'File created')
      ignore_errors: yes

    - name: reboot
      command: "reboot"
      async: 1
      poll: 0
      ignore_errors: yes
      when:
      - (kargs.msg == 'Block inserted') or (kargs.msg == 'File created')
      - wl_enable_reboot | default('true') | bool
      - kernel_args_reboot_required | default('false') | bool

    - name: wait for the machine to come back
      wait_for_connection:
        connect_timeout: 1
        sleep: 1
        delay: 1
        timeout: 1800
      ignore_errors: yes
      when:
      - (kargs.msg == 'Block inserted') or (kargs.msg == 'File created')
      - wl_enable_reboot | default('true') | bool
      - kernel_args_reboot_required | default('false') | bool

