#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
- hosts: workload_hosts
  become: yes
  any_errors_fatal: true
  gather_facts: no
  tasks:

    - name: Install docker
      include_role:
        name: docker
      when:
      - ansible_connection != 'winrm'
      - (native | default(false) | bool) == false

