
- block:

    - name: create config.yaml
      template:
        src: "{{ k8s_registry_storage }}-config.yaml.j2"
        dest: "/tmp/{{ wl_namespace }}-registry-config.yaml"
        owner: root
        mode: "0400"
      become: yes

    - name: find home
      shell:
        cmd: "echo $HOME"
        executable: /bin/bash
      register: home

    - name: create config.yaml secret
      command: "kubectl create --kubeconfig={{ home.stdout }}/.kube/config --namespace=wsf-registry secret generic wsf-registry-config --from-file=config.yml=/tmp/{{ wl_namespace }}-registry-config.yaml"
      become: yes

  always:

    - name: delete config.yaml
      file:
        path: "/tmp/{{ wl_namespace }}-registry-config.yaml"
        state: absent
      become: yes

