
  - name: copy cert to workers
    copy:
      src: "/tmp/{{ wl_namespace }}-registry-cert-{{ k8s_registry_ip }}:{{ k8s_registry_port }}-{{ ansible_host }}.crt"
      dest: "/etc/pki/ca-trust/source/anchors/registry.crt"
    become: yes

  - name: update certificates
    command: update-ca-trust
    become: yes

