
### Gloabl Configuration ###
REGISTRY: ""
RELEASE: ""
PLATFORM: ""
BACKEND: ""

### Workload Configuration ###
WORKLOAD: ""
TESTCASE: ""

DEBUG: false
DB_TYPE: "mysql"
DB_PORT: "3306"
DB_FS_TYPE: "disk"
DB_HUGEPAGE_STATUS: "off"
DB_DATASIZE_OF_WAREHOUSE_RATIO: "0.1"
DB_BUFFERSIZE_OF_DATASIZE_RATIO: "0.75"
DB_HUGEPAGES_2MI: "1Gi"
DB_HUGEPAGES: "512"

DB_CPU_LIMIT: "8"
DB_CPU_REQUEST: "1"
### Database Configuration ###
DB_SERVICE: "db-service"
DB_VERSION: "8031"
MYSQL_USECASE: "base"

###### MySQL Configuration ######
MYSQL_USER: "root"
MYSQL_ROOT_PASSWORD: "Mysql@123"
MYSQL_STORAGE_ENGINE: "innodb"
MYSQL_CONFIG_PATH: "/etc/mysql/conf.d/mysql.cnf"
MYSQL_MOUNT_PATH: "/var/lib/mysql"
MYSQL_LOG_DIR: "/var/log/mysql"
MYSQL_ERROR_LOG: "error.log"

# MySQL config simplified
MYSQL_CONFIG_SIMPILIFIED: false
### Mysql exposed parameters
MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: "mysql_native_password"
# Benchmarking only.  To be removed for production configuration.
MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT: "0"
MYSQL_INNODB_FLUSH_METHOD: "O_DIRECT_NO_FSYNC"
MYSQL_INNODB_DOUBLEWRITE: "0"
# general
MYSQL_MAX_CONNECTIONS: "4000"
MYSQL_TABLE_OPEN_CACHE: "8000"
MYSQL_TABLE_OPEN_CACHE_INSTANCES: "16"
MYSQL_BACK_LOG: "1500"
MYSQL_MAX_PREPARED_STMT_COUNT: "128000"
MYSQL_PERFORMANCE_SCHEMA: "OFF"
MYSQL_INNODB_OPEN_FILES: "4000"
# buffers
MYSQL_INNODB_BUFFER_POOL_SIZE: "4G" # default for xlarge case
MYSQL_INNODB_LOG_BUFFER_SIZE: "64M"
MYSQL_INNODB_LOG_FILE_SIZE: "1024M"
MYSQL_INNODB_BUFFER_POOL_INSTANCES: "16"
MYSQL_INNODB_LOG_FILES_IN_GROUP: "32"
# legacy
MYSQL_DEFAULT_PASSWORD_LIFETIME: "0"
MYSQL_SSL: "0"
MYSQL_SKIP_LOG_BIN: "1"
MYSQL_CHARACTER_SET_SERVER: "latin1"
MYSQL_COLLATION_SERVER: "latin1_swedish_ci"
MYSQL_TRANSACTION_ISOLATION: "REPEATABLE-READ"
MYSQL_INNODB_FILE_PER_TABLE: "ON"
MYSQL_INNODB_THREAD_CONCURRENCY: "0"
MYSQL_INNODB_MAX_DIRTY_PAGES_PCT: "90"
MYSQL_INNODB_MAX_DIRTY_PAGES_PCT_LWM: "10"
MYSQL_JOIN_BUFFER_SIZE: "32K"
MYSQL_SORT_BUFFER_SIZE: "32K"
MYSQL_INNODB_USE_NATIVE_AIO: "1"
MYSQL_INNODB_SPIN_WAIT_DELAY: "6"
MYSQL_INNODB_STATS_PERSISTENT: "1"
MYSQL_INNODB_MAX_PURGE_LAG_DELAY: "300000"
MYSQL_INNODB_MAX_PURGE_LAG: "0"
MYSQL_INNODB_CHECKSUM_ALGORITHM: "none"
MYSQL_INNODB_IO_CAPACITY: "4000"
MYSQL_INNODB_IO_CAPACITY_MAX: "20000"
MYSQL_INNODB_LRU_SCAN_DEPTH: "9000"
MYSQL_INNODB_CHANGE_BUFFERING: "none"
MYSQL_INNODB_READ_ONLY: "0"
MYSQL_INNODB_PAGE_CLEANERS: "4"
MYSQL_INNODB_UNDO_LOG_TRUNCATE: "off"
MYSQL_INNODB_ADAPTIVE_FLUSHING: "1"
MYSQL_INNODB_FLUSH_NEIGHBORS: "0"
MYSQL_INNODB_READ_IO_THREADS: "16"
MYSQL_INNODB_WRITE_IO_THREADS: "16"
MYSQL_INNODB_PURGE_THREADS: "4"
MYSQL_INNODB_ADAPTIVE_HASH_INDEX: "0"
MYSQL_THREAD_CACHE_SIZE: "300"

### WSF optimized
MYSQL_INNODB_SPIN_WAIT_PAUSE_MULTIPLIER: "50"
MYSQL_INNODB_SYNC_SPIN_LOOPS: "30"
MYSQL_INNODB_PAGE_SIZE: "16K"

###### Postgres Configuration ######
PG_SUPERUSER: "postgres"
PG_SUPERUSERPASS: "Postgres@123"
PG_DEFAULTDBASE: "postgres"
PG_CONFIG_PATH: "/etc/postgresql/postgresql.conf"
PG_DATA: "/var/lib/postgresql/data/pgdata"
PG_MOUNT_PATH: "/var/lib/postgresql/data"

### postgresql.conf
PG_LISTEN_ADDRESSES: "*"
PG_MAX_CONNECTIONS: "256"
PG_SHARED_BUFFERS: "4GB"
PG_TEMP_BUFFERS: "4096MB"
PG_WORK_MEM: "4096MB"
PG_MAINTENANCE_WORK_MEM: "512MB"
PG_AUTOVACUUM_WORK_MEM: "-1"
PG_MAX_STACK_DEPTH: "7MB"
PG_DYNAMIC_SHARED_MEMORY_TYPE: "posix"
PG_MAX_FILES_PER_PROCESS: "4000"
#PG_BGWRITER_DELAY: "200"
#PG_BGWRITER_LRU_MAXPAGES: "100"
#PG_BGWRITER_LRU_MULTIPLIER: "2.0"
PG_EFFECTIVE_IO_CONCURRENCY: "32"
#PG_MAX_WORKER_PROCESSES: "64"
PG_WAL_LEVEL: "minimal"
PG_SYNCHRONOUS_COMMIT: "off"
PG_WAL_BUFFERS: "512MB"
#PG_WAL_WRITER_DELAY: "200"
PG_CHECKPOINT_TIMEOUT: "1h"
PG_MAX_WAL_SIZE: "524288"
PG_MIN_WAL_SIZE: "8192"
PG_CHECKPOINT_COMPLETION_TARGET: "0.9"
PG_CHECKPOINT_WARNING: "-1"
PG_ARCHIVE_MODE: "off"
PG_MAX_WAL_SENDERS: "0"
PG_RANDOM_PAGE_COST: "1.1"
PG_CPU_TUPLE_COST: "0.03"
PG_EFFECTIVE_CACHE_SIZE: "350GB"
#PG_DEFAULT_STATISTICS_TARGET: "100"
PG_TRACK_ACTIVITY_QUERY_SIZE: "2048"
PG_LOG_MIN_MESSAGES: "error"
PG_LOG_MIN_ERROR_STATEMENT: "error"
PG_LOG_TIMEZONE: "Etc/UTC"
PG_AUTOVACUUM: "on"
PG_AUTOVACUUM_MAX_WORKERS: "10"
#PG_AUTOVACUUM_FREEZE_MAX_AGE: "1000000000"
PG_AUTOVACUUM_VACUUM_COST_LIMIT: "3000"
#PG_VACUUM_FREEZE_MIN_AGE: "10000000"
PG_DATESTYLE: "iso"
PG_TIMEZONE: "Etc/UTC"
PG_LC_MESSAGES: "en_US.UTF-8"
PG_LC_MONETARY: "en_US.UTF-8"
PG_LC_NUMERIC: "en_US.UTF-8"
PG_LC_TIME: "en_US.UTF-8"
PG_DEFAULT_TEXT_SEARCH_CONFIG: "pg_catalog.english"
PG_MAX_LOCKS_PER_TRANSACTION: "64"
PG_MAX_PRED_LOCKS_PER_TRANSACTION: "64"
###

###### HammerDB Configuration ######
TPCC_NUM_WAREHOUSES: "50" # default for xlarge case
TPCC_THREADS_BUILD_SCHEMA: "4" # default for xlarge case
TPCC_HAMMER_NUM_VIRTUAL_USERS: "9_9_9" # default for xlarge case
TPCC_MINUTES_OF_RAMPUP: "2"
TPCC_RUNTIMER_SECONDS: "600"
TPCC_MINUTES_OF_DURATION: "5"
TPCC_TOTAL_ITERATIONS: "10000000"
TPCC_INIT_MAX_WAIT_SECONDS: "30"
TPCC_WAIT_COMPLETE_MILLSECONDS: "5000"
TPCC_TCL_SCRIPT_PATH: "/tcls"
TPCC_HAMMER_NUM_VIRTUAL_USERS_GEN_ALGORITHM: "fixed"
TPCC_VUSERS_STEPS: "8"
TPCC_ASYNC_SCALE: false
TPCC_CONNECT_POOL: false
TPCC_TIMEPROFILE: false

### External parameters
RUN_SINGLE_NODE: false
ENABLE_SOCKET_BIND: false
SERVER_SOCKET_BIND_NODE: ""
SERVER_SOCKET_BIND_CORE_LIST: ""
CLIENT_SOCKET_BIND_NODE: ""
CLIENT_SOCKET_BIND_CORE_LIST: ""
ENABLE_MOUNT_DIR: true
MOUNT_DIR: "/mnt/disk1"
SERVER_CORE_NEEDED_FACTOR: "0.9"
ENABLE_RPSRFS_AFFINITY: true
RPS_SOCK_FLOW_ENTRIES: 32768
ENABLE_IRQ_AFFINITY: true
EXCLUDE_IRQ_CORES: false
DB_RUN_PLATFORM: "x86"
ENABLE_TUNING: true

