
- name: Install trace module
  include_tasks:
    file: trace-block.yaml
  when: trace_module == 'gprofiler'
  loop: "{{ (wl_trace_modules | default('')).split(',') }}"
  loop_control:
    loop_var: trace_module
  ignore_errors: yes

- name: Restart kubelet for huge pages
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
  changed_when: false
  become: true
  check_mode: false
  failed_when: false
  when:
    - (csp | default('static')) == 'static' and (k8s_reset | default('false') | bool) == false
    - ( (k8s_node_labels | default([]) | join(' ')) is match('.*HAS-SETUP-HUGEPAGE-.*') )

- name: Customize workers
  include_role:
    name: installation
    tasks_from: customize
  when: (role_path + '/tasks/customize.yaml') is exists

