#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#


- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
  become: true