
- name: Create the numastat directory
  file:
    path: "{{ wl_logs_dir}}/{{ trace_node.1 }}-{{ itr | default(1) }}-numastat"
    state: directory
  delegate_to: localhost
  become: no
  ignore_errors: yes

- name: Fetch numastat files
  fetch:
    src: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-numastat.logs"
    dest: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-numastat/numastat.logs"
    flat: yes
  become: no
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes

- name: Remove any collection files
  file:
    path: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-numastat.logs"
    state: absent
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes

- name: Remove any collection files
  file:
    path: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-numastat.pid"
    state: absent
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes
