#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Install numactl
  yum:
    name:
      - numactl
    update_cache: true
  become: yes
  register: yumrc
  until: yumrc is success
  retries: 10
  delay: 10
