
- name: "Stop numastat on {{ trace_node.1 }}"
  shell:
    cmd: "kill -9 $(cat /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-numastat.pid)"
    executable: /bin/bash
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes
  async: 5
  poll: 0
