
perf_record_options: "-a -g"
perf_report_options: "--header"
perf_fetch_data: no
perf_script_options: ""
perf_flamegraph: no
perf_flamegraph_collapse_options: "--all"
perf_flamegraph_svg_options: "--color=java --hash"
perf_collection_time: 10
perf_action: "record"
perf_stat_options: "-a -I 500 -e cycles -e instructions"
perf_options: "{{ (perf_action == 'stat') | ternary(perf_stat_options, perf_record_options) }}"
