#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

  - name: copy cert to workers
    copy:
      src: "{{ item.path }}"
      dest: "/usr/local/share/ca-certificates/wsf-{{ item.path | basename }}"
    loop: "{{ certs.files }}"

  - name: update certificates
    command: update-ca-certificates

