#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Install openssl
  yum:
    name: openssl
    state: present
    update_cache: yes
  register: yumrc
  until: yumrc is success
  retries: 10
  delay: 10

