#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# For Alicloud use specific tier multipler(s) and then allow the following expression [*_specjbb_2015_openjdk_multijvm*pkm] to override the rest of the values
*_alicloud_specjbb_2015_openjdk_multijvm*pkm:
  SPECJBB_DEFAULT_T1_T2_T3_MULTIPLIERS: "2,1,1"

*_specjbb_2015_openjdk_multijvm*pkm:
  JDK_PACKAGE: ${JDK_PACKAGE:-'17.0.1'}
  SPECJBB_TUNE_OPTION: max
  SPECJBB_BACKEND_SURVIVOR_RATIO: ${SPECJBB_BACKEND_SURVIVOR_RATIO:-28}
  SPECJBB_HUGE_PAGE_SIZE: ${SPECJBB_HUGE_PAGE_SIZE:-2m}

*_specjbb_2015_openjdk_multijvm*gated:
  JDK_PACKAGE: ${JDK_PACKAGE:-'17.0.1'}
  SPECJBB_TUNE_OPTION: regular
  SPECJBB_BACKEND_SURVIVOR_RATIO: ${SPECJBB_BACKEND_SURVIVOR_RATIO:-28}
  SPECJBB_HUGE_PAGE_SIZE: ${SPECJBB_HUGE_PAGE_SIZE:-2m}

*_specjbb_2015_zulu_multijvm_*pkm:
  JDK_PACKAGE: ${JDK_PACKAGE:-19.30.11}
  SPECJBB_TUNE_OPTION: max
  SPECJBB_BACKEND_SURVIVOR_RATIO: ${SPECJBB_BACKEND_SURVIVOR_RATIO:-28}
  SPECJBB_HUGE_PAGE_SIZE: ${SPECJBB_HUGE_PAGE_SIZE:-2m}

*_specjbb_2015_zulu_multijvm_*gated:
  JDK_PACKAGE: ${JDK_PACKAGE:-19.30.11}
  SPECJBB_TUNE_OPTION: regular
  SPECJBB_BACKEND_SURVIVOR_RATIO: ${SPECJBB_BACKEND_SURVIVOR_RATIO:-28}
  SPECJBB_HUGE_PAGE_SIZE: ${SPECJBB_HUGE_PAGE_SIZE:-2m}  

*_specjbb_2015_openjdk_composite_gated:
  JDK_PACKAGE: ${JDK_PACKAGE:-'17.0.1'}
  SPECJBB_TUNE_OPTION: regular
  SPECJBB_BACKEND_SURVIVOR_RATIO: ${SPECJBB_BACKEND_SURVIVOR_RATIO:-28}
  SPECJBB_HUGE_PAGE_SIZE: ${SPECJBB_HUGE_PAGE_SIZE:-2m}

*_specjbb_2015_openjdk_composite_base:
  JDK_PACKAGE: ${JDK_PACKAGE:-'17.0.1'}
  SPECJBB_TUNE_OPTION: ${SPECJBB_TUNE_OPTION:-max}
  SPECJBB_BACKEND_SURVIVOR_RATIO: ${SPECJBB_BACKEND_SURVIVOR_RATIO:-28}
  SPECJBB_HUGE_PAGE_SIZE: ${SPECJBB_HUGE_PAGE_SIZE:-2m}