
- name: Create the emon directory
  file:
    path: "{{ wl_logs_dir}}/{{ trace_node.1 }}-{{ itr | default(1) }}-emon"
    state: directory
  delegate_to: localhost
  become: no
  ignore_errors: yes

- name: Fetch emon files
  fetch:
    src: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-emon.dat"
    dest: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-emon/emon.dat"
    flat: yes
  become: no
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes

- name: Remove any collection files
  file:
    path: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-emon.dat"
    state: absent
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes

- name: Remove any collection files
  file:
    path: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-emon.pid"
    state: absent
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes

- name: Post Processing
  include_tasks:
    file: edp-post-processing.yaml
  when: emon_post_processing
