#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

  - name: "Start emon on {{ trace_node.1 }}"
    shell: 
      cmd: |
        . ./sep_vars.sh
        date -Ins > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-emon.start
        emon -collect-edp {{ emon_options }} > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-emon.dat 2>&1 &
        echo $! > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-emon.pid
        disown
      chdir: "{{ emon_bin_path }}/sep"
      executable: /bin/bash
    async: 5
    poll: 0
    become: yes
    delegate_to: "{{ trace_node.1 }}"
    ignore_errors: yes

