
- name: "Stop emon on {{ trace_node.1 }}"
  shell:
    cmd: |
      . ./sep_vars.sh
      emon -stop
      sleep 5
      kill -9 $(cat "{{ wl_namespace }}-{{ trace_node.1 }}-emon.pid")
    chdir: "{{ emon_bin_path }}/sep"
    executable: /bin/bash
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes
  async: 5
  poll: 0

