
- name: Create the gprofiler directory
  file:
    path: "{{ wl_logs_dir}}/{{ trace_node.1 }}-{{ itr | default(1) }}-gprofiler"
    state: directory
  delegate_to: localhost
  become: no
  failed_when: false

- name: Archive gprofiler files
  command:
    cmd: "tar cfz /tmp/{{ wl_namespace }}-gprofiler.tgz ."
    chdir: "/tmp/{{ wl_namespace }}-gprofiler"
  become: no
  delegate_to: "{{ trace_node.1 }}"
  failed_when: false

- name: Fetch gprofiler files
  fetch:
    src: "/tmp/{{ wl_namespace }}-gprofiler.tgz"
    dest: "{{ wl_logs_dir }}/"
    flat: yes
  become: no
  delegate_to: "{{ trace_node.1 }}"
  failed_when: false

- name: Untar gprofiler files
  command:
    cmd: "tar xfz {{ wl_logs_dir }}/{{ wl_namespace }}-gprofiler.tgz"
    chdir: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-gprofiler"
  delegate_to: localhost
  become: no
  failed_when: false

- name: Remove any collection files
  file:
    path: "/tmp/{{ wl_namespace }}-gprofiler"
    state: absent
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  failed_when: false

- name: Remove any gprofiler tar files
  file:
    path: "/tmp/{{ wl_namespace }}-gprofiler.tgz"
    state: absent
  become: no
  delegate_to: "{{ trace_node.1 }}"
  failed_when: false

- name: Remove any gprofiler yaml files
  file:
    path: "/tmp/{{ wl_namespace }}-gprofiler.yaml"
    state: absent
  become: no
  delegate_to: "{{ trace_node.1 }}"
  failed_when: false

