#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if gprofiler is already installed
  stat:
    path: /usr/local/bin/gprofiler
  register: gprofiler

- name: Get uname -m
  command: uname -m
  register: uname
  when: not gprofiler.stat.exists

- name: Fetch gprofiler
  get_url:
    url: "{{ gprofiler_package }}/gprofiler_{{ uname.stdout }}"
    dest: /usr/local/bin/gprofiler
    mode: "a+rx"
  become: true
  when: not gprofiler.stat.exists

