#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: "start gprofiler on {{ trace_node.1 }}"
  shell:
    cmd: |
      mkdir -p /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-gprofiler
      cd /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-gprofiler
      date -Ins > TRACE_START
      /usr/local/bin/gprofiler {{ gprofiler_options }} --continuous --output /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-gprofiler > gprofiler.logs 2>&1 &
      echo $! > pid
      disown
  delegate_to: "{{ trace_node.1 }}"
  become: true
  ignore_errors: true
  async: 5
  poll: 0

