
- name: "Stop gprofiler on {{ trace_node.1 }}"
  command: "docker rm -f granulate-gprofiler"
  delegate_to: "{{ trace_node.1 }}"
  when: trace_from == "docker"
  failed_when: false
  async: 5
  poll: 0

- name: Stop gprofiler daemonset
  command: "kubectl delete -f /tmp/{{ wl_namespace }}-gprofiler.yaml"
  when:
  - trace_from == "kubernetes"
  - trace_node.1 == (groups['trace_hosts'] | list | last)
  failed_when: false
  async: 5
  poll: 0

