#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: get trace mode
  set_fact:
    trace_mode: "{{ 'trace_mode' | extract(lookup('file', wl_logs_dir + '/workload-config.yaml') | from_yaml) | split(',') }}"

- name: workload execution procedure
  block:

    - name: waitproc to wait for logs complete
      shell:
        cmd: |
          timeout {{ workload_config.timeout.split(',') | first }}s bash -c 'docker exec {{ off_cluster_container_id }} cat {{ workload_config.export_logs }} > /tmp/{{ wl_namespace }}-docker-logs.tar' > /dev/null 2>&1 &
          echo $!
          disown
        executable: /bin/bash
      register: waitproc
      delegate_to: "{{ off_cluster_host }}"
      vars:
        workload_config: "{{ lookup('file', wl_logs_dir+'/workload-config.yaml') | from_yaml }}"

    - name: "wait for the starting phrase: {{ trace_mode[1] }}"
      shell:
        cmd: |
          while kill -0 {{ waitproc.stdout_lines | first }}; do
            docker logs {{ off_cluster_container_id }} | grep -q -F "{{ trace_mode[1] }}" && break
            bash -c 'sleep 0.1'
          done
        executable: /bin/bash
      when: (trace_mode | first == "roi")
      ignore_errors: yes
      delegate_to: "{{ off_cluster_host }}"

    - name: "wait for timeout {{ trace_mode[1] }}s"
      command: |
        timeout {{ trace_mode[1] | int }}s tail --pid={{ waitproc.stdout_lines | first }} -f /dev/null
      when: (trace_mode | first == "time")
      ignore_errors: yes
      delegate_to: "{{ off_cluster_host }}"

    - name: start trace
      include_role:
        name: trace
        tasks_from: start
      when: wl_trace_modules is defined

    - name: "wait for the stop phrase: {{ trace_mode[2] }}"
      shell:
        cmd: |
          while kill -0 {{ waitproc.stdout_lines | first }}; do
            docker logs {{ off_cluster_container_id }} | grep -q -F "{{ trace_mode[2] }}" && break
            bash -c 'sleep 0.1'
          done
        executable: /bin/bash
      when: (trace_mode | first == "roi")
      ignore_errors: yes
      delegate_to: "{{ off_cluster_host }}"

    - name: "wait for timeout {{ trace_mode[2] }}s"
      command: |
        timeout {{ trace_mode[2] | int }}s tail --pid={{ waitproc.stdout_lines | first }} -f /dev/null
      when: (trace_mode | first == "time")
      ignore_errors: yes
      delegate_to: "{{ off_cluster_host }}"

    - name: revoke trace
      include_role:
        name: trace
        tasks_from: stop
      when:
      - wl_trace_modules is defined
      - (trace_mode | length == 3)

    - name: wait until execution compete
      command: "tail --pid={{ waitproc.stdout_lines | first }} -f /dev/null"
      ignore_errors: yes
      delegate_to: "{{ off_cluster_host }}"

  always:

    - name: revoke trace
      include_role:
        name: trace
        tasks_from: stop
      when: wl_trace_modules is defined

- name: print docker info
  command: "docker version"
  delegate_to: "{{ off_cluster_host }}"

- name: collect trace data
  include_role:
    name: trace
    tasks_from: collect
  when: wl_trace_modules is defined
  ignore_errors: yes

- name: print docker logs
  command: "docker logs {{ off_cluster_container_id }}"
  ignore_errors: true
  delegate_to: "{{ off_cluster_host }}"

- name: create the iteration direcctory
  file:
    path: "{{ wl_logs_dir }}/itr-{{ itr }}/{{ off_cluster_container_id }}"
    state: directory
  delegate_to: localhost

- name: copy logs back to the itr directory
  fetch:
    src: "/tmp/{{ wl_namespace }}-docker-logs.tar"
    dest: "{{ wl_logs_dir }}/itr-{{ itr }}/"
    flat: yes
  delegate_to: "{{ off_cluster_host }}"

- name: untar the logs
  unarchive:
    src: "{{ wl_logs_dir }}/itr-{{ itr }}/{{ wl_namespace }}-docker-logs.tar"
    dest: "{{ wl_logs_dir}}/itr-{{ itr }}/{{ off_cluster_container_id }}"
  delegate_to: localhost
  ignore_errors: true

- name: remove remote logs
  file:
    path: "/tmp/{{ wl_namespace }}-docker-logs.tar"
    state: absent
  delegate_to: "{{ off_cluster_host }}"

- name: remove local logs tarfile
  file:
    path: "{{ wl_logs_dir }}/itr-{{ itr }}/{{ wl_namespace }}-docker-logs.tar"
    state: absent
  delegate_to: localhost
