- name: Check if istio installed
  shell:
    cmd: "which istioctl"
  ignore_errors: true
  register: istio_installed

- name: Uninstall istio
  become: true
  become_user: "{{ ansible_user }}"
  shell:
    cmd: "istioctl uninstall --purge -y"
  when: istio_installed.rc == 0
  ignore_errors: true
