#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Create the perf directory
  file:
    path: "{{ wl_logs_dir}}/{{ trace_node.1 }}-{{ itr | default(1) }}-perf"
    state: directory
  delegate_to: localhost
  become: no
  ignore_errors: yes

- name: Process perf records
  shell: "perf report {{ perf_report_options }} -i /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.record > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.report"
  delegate_to: "{{ trace_node.1 }}"
  register: report
  become: yes
  ignore_errors: yes
  when: perf_action == "record"

- name: Fetch perf files
  fetch:
    src: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.report"
    dest: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-perf/perf.report"
    flat: yes
  delegate_to: "{{ trace_node.1 }}"
  become: yes
  ignore_errors: yes
  when: perf_action == "record"

- name: Fetch perf raw data
  fetch:
    src: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.record"
    dest: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-perf/perf.data"
    flat: yes
  delegate_to: "{{ trace_node.1 }}"
  become: yes
  ignore_errors: yes
  when: perf_fetch_data or perf_action == "stat"

- name: Fetch trace start/stop timing
  fetch:
    src: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.{{ item.src }}"
    dest: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-perf/{{ item.dest }}"
    flat: yes
  delegate_to: "{{ trace_node.1 }}"
  become: yes
  ignore_errors: yes
  loop:
  - src: start
    dest: TRACE_START
  - src: stop
    dest: TRACE_STOP

- name: Create flame graph
  include_tasks:
    file: flamegraph.yaml
  when: perf_flamegraph and perf_action == "record"

- name: Remove any collection files
  file:
    path: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.{{ item }}"
    state: absent
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes
  loop:
  - record
  - data
  - pid
  - start
  - stop

