#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#


- name: uname -r
  command: uname -r
  register: unamer

- name: Install perf
  apt:
    name:
      - linux-tools-common
      - linux-tools-generic
      - "linux-tools-{{ unamer.stdout }}"
    update_cache: true
    state: present
  become: yes
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10



