#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

  - name: "Start perf on {{ trace_node.1 }}"
    shell:
      cmd: |
        date -Ins > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.start
        perf {{ perf_action }} {{ perf_options }} --output /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.record -- sleep {{ perf_collection_time }} > /dev/null 2>&1 &
        echo $! > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.pid
        disown
      executable: /bin/bash
    async: 5
    poll: 0
    become: yes
    delegate_to: "{{ trace_node.1 }}"
    ignore_errors: yes

