
- name: "Stop perf on {{ trace_node.1 }}"
  shell: 
    cmd: "kill $(cat /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.pid)"
    executable: /bin/bash
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes
  async: 5
  poll: 0

