#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# test-config-customize.yaml
# Overwrite the test cases for customization.
######################### BKM for Workload Performance#######################
# SPECJBB_TIER_1_THREADS/SPECJBB_TIER_2_THREADS/SPECJBB_TIER_3_THREADS are the number of worker threads in the 3-Tier model of specjbb.
# At first, suggest to set these 3 parameters with the below formula:
# SPECJBB_TIER_1_THREADS=(6.2 x logic_core_number/NUMA nodes)
# SPECJBB_TIER_2_THREADS=(0.2 x logic_core_number/NUMA nodes)
# SPECJBB_TIER_3_THREADS=(1.25 x logic_core_number/NUMA nodes)
# Then you can optimize these parameters to get better performance.
#
# SPECJBB_XMX is an important parameter which stands for the heap size of each 
# Backend. If the value is huge, the garbage collection may take a lot of 
# time so that the test will fail after a period of time. If the value is 
# very low, the test will also fail because only a few java objects could 
# be created at the same time.
#
# The group count should be equal to numa nodes count.
# You can check the numa nodes count with "numactl -H | grep cpus | wc -l"
# 
# The total hugepage needed is calculated by this formula: 
# (SPECJBB_XMX x SPECJBB_GROUPS + 2 x SPECJBB_GROUPS + 2). Here the first "2" means the 
# heap size of transaction injector and the second "2" stands for the heap 
# size used by controller.
#
# The total hugepage amount should not be larger than free memory of the 
# system under test. Otherwise the system may crash after set the hugepage 
# or when running this workload.
#
# Since every system has its own suitable configurations, the parameters
# listed in this file may not lead to the best performance. And when meet 
# the issue that kpi is 0 and test case passed, reduce SPECJBB_TIER_1_THREADS/SPECJBB_TIER_2_THREADS/SPECJBB_TIER_3_THREADS may help.
############################################################################

*_main:
  SPECJBB_TIER_1_THREADS: 16
  SPECJBB_TIER_2_THREADS: 2
  SPECJBB_TIER_3_THREADS: 4
  SPECJBB_XMX: 4g
  SPECJBB_GROUPS: 1

*_pkm:
  SPECJBB_TIER_1_THREADS: 16
  SPECJBB_TIER_2_THREADS: 2
  SPECJBB_TIER_3_THREADS: 4
  SPECJBB_XMX: 4g
  SPECJBB_GROUPS: 1