# test-config-spr.yaml
# Overwrite the test cases for performance tunning on SPR.
######################### BKM for Workload Performance###########################
# SPECJBB_TIER_1_THREADS/SPECJBB_TIER_2_THREADS/SPECJBB_TIER_3_THREADS are the number of worker threads in the 3-Tier model of specjbb.
#
# SPECJBB_XMX is an important parameter which stands for the heap size of each 
# Backend. If the value is huge, the garbage collection may take a lot of 
# time so that the test will fail after a period of time. If the value is 
# very low, the test will also fail because only a few java objects could 
# be created at the same time.
#
# The group count should be equal to numa nodes count, by default the numa 
# nodes count of SPR is 2. When SNC-4 is enabled, there are 8 numa nodes, 
# in this scenario the recommanded SPECJBB_GROUPS is 8.
# 
# The total hugepage needed is calculated by this formula: 
# (SPECJBB_XMX x SPECJBB_GROUPS + 2 x SPECJBB_GROUPS + 2 + 2). Here the first "2" means the 
# heap size of transaction injector and the second "2" stands for the heap 
# size used by controller. Besides, we need 2GB more for JVM to store some other
# runtime data, otherwise there might be a core dump error during the test.
#
# The total hugepage amount should not be larger than free memory of the 
# system under test. Otherwise the system may crash after set the hugepage 
# or when running this workload.
#
# Since every system has its own suitable configurations, the parameters
# listed in this file may not lead to the best performance. And when meet 
# the issue that kpi is 0 and test case passed, reduce SPECJBB_TIER_1_THREADS/SPECJBB_TIER_2_THREADS/SPECJBB_TIER_3_THREADS may help.
#################################################################################

*_main:
  SPECJBB_TIER_1_THREADS: 224
  SPECJBB_TIER_2_THREADS: 5
  SPECJBB_TIER_3_THREADS: 29
  SPECJBB_XMX: 29g
  SPECJBB_GROUPS: 2

*_pkm:
  SPECJBB_TIER_1_THREADS: 224
  SPECJBB_TIER_2_THREADS: 5
  SPECJBB_TIER_3_THREADS: 29
  SPECJBB_XMX: 29g
  SPECJBB_GROUPS: 2