
- name: collect trace data
  include_tasks:
    file: collect-block.yaml
  loop: "{{ wl_trace_modules | default() | split(',') | product([inventory_hostname]) | list }}"
  loop_control:
    loop_var: trace_node
  ignore_errors: yes

