
- name: start trace
  include_tasks:
    file: start-block.yaml
  loop: "{{ wl_trace_modules | default() | split(',') | product([inventory_hostname]) | list }}"
  loop_control:
    loop_var: trace_node
  ignore_errors: yes

- name: set trace started
  set_fact:
    trace_started: true
    cacheable: true

