#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: start trace
  include_tasks:
    file: start-block.yaml
  loop: "{{ wl_trace_modules | default() | split(',') | product(groups['trace_hosts']) | list }}"
  loop_control:
    loop_var: trace_node
  ignore_errors: yes

- name: set trace started
  set_fact:
    trace_started: true
    cacheable: true

