#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: stop trace
  include_tasks:
    file: stop-block.yaml
  loop: "{{ wl_trace_modules | default() | split(',') | product(groups['trace_hosts']) | list }}"
  loop_control:
    loop_var: trace_node
  when: trace_started | default(false) == true
  ignore_errors: yes

- name: clear trace started
  set_fact:
    trace_started: false
    cacheable: true

