#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#


- name: Prerequisite of calicovpp
  include_role:
    name: cni-calicovpp
    tasks_from: prerequisite.yaml
  when: k8s_cni == "calicovpp"
