#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: "{{ .Values.name }}-{{ now }}"
  namespace: "{{ .Values.NAMESPACE }}"
rules:
  - apiGroups:
      - topo.onosproject.org
    resources:
      - '*'
    verbs:
      - '*'
