#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.name }}-{{ now }}"
  namespace: "{{ .Values.NAMESPACE }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.NAMESPACE }}"
roleRef:
  kind: ClusterRole
  name: "{{ .Values.name }}"
  apiGroup: rbac.authorization.k8s.io