#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Install prerequisites
  package:
    name: 
    - cmake
    - make
    - m4
    - gawk
    state: present
  register: pkgrc
  until: pkgrc is success
  retries: 10
  delay: 10
