#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

image:
  name: cm-xapp
  pullPolicy: IfNotPresent
service:
  name: cm-xapp
resources:
  requests_cpu: 2
  requests_memory: 2Gi
  limits_cpu: 2
  limits_memory: 2Gi
  requests_proxy_cpu: 1
  requests_proxy_memory: 2Gi
  limits_proxy_cpu: 1
  limits_proxy_memory: 2Gi

name: cm-xapp

parameters:
  xAppRunTime: 1080
  logLevel: info
  initiationTime: 120
  cellIndLimit: 1000
  file:
  parallelLoop: true
  qValue: 10
  preprocessing: false
  corebind: 0


sd-ran:
  import:
    onos-a1t:
      enabled: false

ran-simulator:
  pci:
    modelName: model-7cell-140ue.yaml
