#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if collectd is already installed
  stat:
    path: "{{ collectd_bin_path }}"
  register: collectd

- name: Check OS
  shell:
    cmd: ". /etc/os-release; echo $ID"
    executable: /bin/bash
  register: os

- name: Install collectd
  include_tasks:
    file: "install-{{ os.stdout }}.yaml"

- name: Detect collectd version
  command: "{{ collectd_bin_path }} -h"
  register: version

- name: Install collectd.conf
  template:
    src: collectd.conf.j2
    dest: "{{ config_path }}"
  become: yes

- name: Stop collectd
  service:
    name: collectd
    enabled: no
    state: stopped
  become: yes

- name: Remove any collection files
  file:
    path: "{{ collectd_csv_path }}/"
    state: absent
  become: yes

