
  - name: "Start collectd on {{ trace_node.1 }}"
    shell:
      cmd: |
        {{ collectd_bin_path }} -f > /dev/null 2>&1 &
        echo $! > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-collectd.pid
        disown
      executable: /bin/bash
    become: yes
    delegate_to: "{{ trace_node.1 }}"
    ignore_errors: yes
    async: 5
    poll: 0
