#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Detect OS
  shell:
    cmd: ". /etc/os-release; echo $ID"
    executable: /bin/bash
  register: os

- name: Install k8s
  include_tasks:
    file: "install-{{ (os.stdout == 'rhel' or os.stdout =='anolis') | ternary('centos', os.stdout) }}.yaml"

- name: Start kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: started
  become: yes

