apiVersion: v1
kind: Service
metadata:
  name: zookeeper-kafka-server-service
  labels:
    name: zookeeper-kafka-server-service
spec:
  ports:
    - port: 2181
      protocol: TCP
      name: zookeeper-kafka-server-1
    - port: 9092
      protocol: TCP
      name: zookeeper-kafka-server-2
    - port: 9093
      protocol: TCP
      name: zookeeper-kafka-server-3
 
  selector:
    app: zookeeper-kafka-server
  type: ClusterIP