---
- name: 'Find Home path'
  ansible.builtin.shell:
    cmd: "echo $HOME"
    executable: /bin/bash
  register: home

- name: 'Create docker auth path'
  ansible.builtin.file:
    path: "{{ home.stdout }}/{{ docker_auth_config_json | dirname }}"
    mode: "0700"
    state: directory
  failed_when: false

- name: 'Copy docker auth'
  ansible.builtin.copy:
    src: "/home/{{ docker_auth_config_json }}"
    dest: "{{ home.stdout }}/{{ docker_auth_config_json }}"
    mode: preserve
    owner: "{{ ansible_user }}"
  failed_when: false
  become: true
