- hosts: "{{ ('controller' in groups) | ternary('controller','localhost') }}"
  gather_facts: no
  tasks:

    - name: Transfer image(s) to docker registry
      include_role:
        name: image-to-registry
      when: ansible_connection != 'winrm'

