- hosts: workload_hosts
  any_errors_fatal: true
  gather_facts: no
  tasks:

    - name: Transfer image(s) to docker daemon
      include_role:
        name: image-to-daemon
      when: 
      - ansible_connection != 'winrm'
      - (native | default(false) | bool) == false

