#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
- hosts: all
  tasks:
    - name: Get full characterization
      include_role:
        name: characterization
      when:
      - ansible_connection != 'winrm'
      - ansible_processor[1] == "GenuineIntel"