#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- hosts: all
  gather_facts: no
  tasks:

    - name: Wait for system to become reachable
      wait_for_connection:
        connect_timeout: 20
        sleep: 1
        delay: 1
        timeout: 1800

- hosts: localhost
  gather_facts: no
  tasks:

    - name: Breakpoint at provisioning
      include_role:
        name: breakpoint
      vars:
        breakpoint: PrepareStage

- hosts: all
  become: true
  any_errors_fatal: true
  gather_facts: no
  tasks:

    - name: Startup sequence
      include_role:
        name: startup
      when: ansible_connection != 'winrm'

    - name: Prepare Docker Auth
      include_role:
        name: docker_auth
      when:
      - ansible_connection != 'winrm'
      - docker_auth_reuse | default(False) | bool

    - name: Install instance watch
      include_role:
        name: instance-watch
      when:
      - ansible_connection != 'winrm'

- hosts: trace_hosts
  become: true
  gather_facts: no
  tasks:

    - name: Install trace module
      include_role:
        name: startup
        tasks_from: trace-block
      when:
      - trace_module != ""
      - ansible_connection != 'winrm'
      loop: "{{ wl_trace_modules | default('') | split(',') }}"
      loop_control:
        loop_var: trace_module

