#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Create the igt directory
  file:
    path: "{{ wl_logs_dir}}/{{ trace_node.1 }}-{{ itr | default(1) }}-igt"
    state: directory
  delegate_to: localhost
  become: no
  ignore_errors: yes

- name: Fetch igt files
  fetch:
    src: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-igt.{{ item.src }}"
    dest: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-igt/{{ item.dest }}"
    flat: yes
  become: no
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes
  loop:
  - src: logs
    dest: igt.logs
  - src: start
    dest: TRACE_START
  - src: stop
    dest: TRACE_STOP

- name: Remove any collection files
  file:
    path: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-igt.{{ item }}"
    state: absent
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes
  loop:
  - logs
  - start
  - stop
  - pid

