
- name: Install intel-gpu-tools
  apt:
    name:
      - intel-gpu-tools
    update_cache: true
    state: present
  become: yes
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10
