#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

  - name: Check if graphics card present on the PCI bus
    shell:
      cmd: lspci -k | egrep "VGA compatible|Display"
    become: yes
    delegate_to: "{{ trace_node.1 }}"
    ignore_errors: yes
    register: chk_vga

  - name: Check if the i915 kernel driver loaded
    shell:
      cmd: lsmod | grep i915
    become: yes
    delegate_to: "{{ trace_node.1 }}"
    ignore_errors: yes
    register: chk_i915_kernel_driver

  - name: "Start intel_gpu_top on {{ trace_node.1 }}"
    shell:
      cmd: |
        date -Ins > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-igt.start
        /usr/bin/intel_gpu_top {{ igt_options }} > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-igt.logs 2>&1 &
        echo $! > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-igt.pid
        disown
      executable: /bin/bash
    async: 5
    poll: 0
    become: yes
    delegate_to: "{{ trace_node.1 }}"
    ignore_errors: yes
    when:
    - chk_vga.rc == 0
    - chk_i915_kernel_driver.rc == 0
