#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
# global k8s facts stored in localhost
- name: "Cluster check over localhost"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Check cluster status"
      ansible.builtin.include_role:
        name: installation
        tasks_from: check-cluster
      when: ansible_connection != 'winrm'

- name: "Cluster hosts preparation"
  hosts: cluster_hosts
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: "Prepare the cluster"
      ansible.builtin.include_role:
        name: installation
        tasks_from: prepare-cluster
      when: ansible_connection != 'winrm'

- name: "Create cluster on controller node"
  hosts: "{{ ('controller' in groups) | ternary('controller','localhost') }}"
  gather_facts: false
  tasks:
    - name: "Create the cluster"
      ansible.builtin.include_role:
        name: installation
        tasks_from: create-cluster
      when: ansible_connection != 'winrm'

- name: "Join workload hosts to controller"
  hosts: workload_hosts
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: "Join workers"
      ansible.builtin.include_role:
        name: installation
        tasks_from: join-workers
      when: ansible_connection != 'winrm'

- name: "Finalize controller installation tasks"
  hosts: "{{ ('controller' in groups) | ternary('controller','localhost') }}"
  gather_facts: false
  tasks:
    - name: "Finalize controller"
      ansible.builtin.include_role:
        name: installation
        tasks_from: finalize-controller
      when: ansible_connection != 'winrm'

- name: "Finalize workload hosts installation tasks"
  hosts: workload_hosts
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: "Finalize workers"
      ansible.builtin.include_role:
        name: installation
        tasks_from: finalize-workers
      when: ansible_connection != 'winrm'
