#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: unset labels on the nodes
  include_tasks:
    file: unset-label.yaml
  loop: "{{ groups['workload_hosts'] }}"
  loop_control:
    loop_var: node

