
- name: "modprobe {{ label_result.item.split('=')[0].split('-')[3:] | join('-') | lower }}"
  set_fact:
    wl_kernel_modules: "{{ wl_kernel_modules + [ label_name.split('=')[0].split('-')[3:] | join('-') | lower ] }}"

