#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- hosts: cluster_hosts
  any_errors_fatal: true
  gather_facts: no
  tasks:

    - name: check for essentials
      include_role:
        name: check

    - name: check for essentials
      include_role:
        name: check
        tasks_from: check-host

- name: 
  import_playbook: ../terraform/template/ansible/kubernetes/installation.yaml
  vars:
    k8s_enable_registry: false
    k8s_node_labels: []
    k8s_enable_nfd: true
    k8s_cni: "flannel"
    wl_enable_reboot: true
    wl_namespace: "install-k8s"

- hosts: cluster_hosts
  any_errors_fatal: true
  become: yes
  gather_facts: no
  tasks:

    - name: Intall Intel Certificate
      include_role:
        name: intel-ca
      when:
      - install_intelca | bool
      - (playbook_dir + '/roles/intel-ca') is exists

