#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- hosts: localhost
  connection: local
  gather_facts: no
  become: true
  tasks:
    
    - name: Create Certificate
      include_role:
        name: dev-cert
        tasks_from: create

    - name: Install certificate
      include_role:
        name: dev-cert
        tasks_from: install


- hosts: cluster_hosts 
  gather_facts: no
  become: true
  tasks:

    - name: Copy the dev-cert to remote
      include_role:
        name: dev-cert
        tasks_from: install


- hosts: localhost
  connection: local
  gather_facts: no
  become: true
  tasks:
    
    - name: Install docker registry
      include_role:
        name: dev-cert
        tasks_from: registry

